blank_issues_enabled: false
contact_links:
  - name: DaniW42 (Chief Development Officer) Twitter Contact
    url: https://twitter.com/DaniW1337
    about: Please ask questions here.
  - name: talentpierre (Deputy Chief Development Officer) Twitter Contact
    url: https://twitter.com/talentpierre
    about: Please ask questions here.
